name: Unofficial Resharper for GitHub
description: Turn Resharper code inspections into GitHub PR annotations
inputs:
  solution:
    description: Path to an .sln file
    required: true
runs:
  using: docker
  image: docker://legitsecurity/resharper-action
  args:
    - sh
    - -c
    - "resharper-action ${INPUT_SOLUTION}${INPUT_REPORT}"
branding:
  color: red
  icon: alert-octagon
